---
title: "About"
output: distill::distill_article
site: distill::distill_website
---


Nicole Rae Baerg

Email: nicole.baerg [at] gmail [dot] com

Google Scholar

Appointments:

Senior Lecturer
Department of Government, University of Essex (2020 – present).

Lecturer
Department of Government, University of Essex (2016-2020).

Assistant Professor of International Organizations
Department of Social Sciences, University of Mannheim (2014-2016).

Post-doctoral Researcher in Quantitative Methods (Political Textual Analysis)
The Political Economy of Reforms, University of Mannheim (2013-2014).

Research Interests:

Comparative Political Economy, Political Institutions, Central Banking, Political Text Analysis, Computational Social Science

Education:

Ph.D. Political Science, Emory University, 2013.
M.A. Political Science, McGill University, 2006.
B.A. (Hons) Economics and International Development Studies, McGill University, 2004.

Book:

Nicole Baerg. Crafting Consensus: Why Central Bankers Change Their Speech and How Speech Changes the Economy. Oxford University Press, USA, 2020.

Author-meets-critics roundtable at APSA (Commentators: Cristina Bodea, Bill Clark, Jeff Frieden, and Christina Schnieder; Chair: Lucy Goodhart), 2020.
Author-meets-critics roundtable at University of Essex (Commentators: Despina Alexiadou, Carola Binder, and Amy Pond; Chair: Carolina Garriga), 2021.
Review by Geoffry Wood
Review by Nicolas W Thompson
Published Journal Articles:

Nicole Baerg and Dominic Duell and Will Lowe. “Central bank communication as public opinion?” Journal of Political Institutions and Political Economy (forthcoming)

Nicole Baerg and Carola Binder “Speaking to the people: Identifying emotional versus factual messages in central bank speeches.” National Institute Economic Review (forthcoming)

Nicole Baerg and Colin Krainin “Divided Committees and Strategic Vagueness.” European Journal of Political Economy, Volume 74, September (2022): 102240.

Nicole Baerg and James Cross “Central Banking in the 21st Century — A Crisis of Accountability?” European Journal of Political Economy, Volume 74, September (2022): 102294.

Nicole Baerg and Mark Hallerberg. “Council Checks of the Commission under the European Semester” Journal of Common Market Studies 60.1 (2022): 58-80.

Nicole Baerg, Julia Gray, and Jakob Willisch. “Opportunistic, not Optimal Delegation: The Political Origins of Central Bank Independence.” Comparative Political Studies 54.6 (2021): 956-988.

Nicole Baerg and Will Lowe. “A textual Taylor rule: Estimating central bank preferences combining topic and scaling methods.” Political Science Research and Methods, 8.1 (2020): 106-122.

Nicole Baerg, Julie Hotchkiss, and Myriam Quispe-Agnoli. “Documenting the Unauthorized: Political Responses to Unauthorized Immigration” Economics and Politics 30.1 (2018): 1-26.

Monkey Cage Blog Post on Elections and the Unauthorized
Nicole Baerg and Mark Hallerberg. “Explaining Instability in the Stability and Growth Pact: The Contribution of Member State Power and Euroskepticism to the Euro Crisis.” Comparative Political Studies 49.7 (2016): 968-1009.

Monkey Cage Blog Post and LSE blog on the EU and fiscal policy
Sanja Štajner, Nicole Baerg, Simone Paolo Ponzetto, and Heiner Stuckenschmidt “Automatic Detection of Speculation in Policy Statements” in NLP+CSS: Workshops on Natural Language Processing and Computational Social Science (2016) ACM.

Nicole Baerg, Will Lowe, Simone Paolo Ponzetto, Heiner Stuckenschmidt and Cäcilia Zirn. “Estimating Central Bank Preferences,” In: Paper entry to the NLP Unshared Task in PoliInformatics. PoliInformatics Research Coordination Network (PInet), [Washington, DC], pp 1-6, (2014). Winning entry

Pablo Aacosta, Nicole Baerg, and Federico Mandelman.“Remittances, Exchange Rate Regimes, and Financial Sector Development: A Panel Data Analysis,” Economic Review, Federal Reserve Bank of Atlanta, pp 1-12, (2009).

Mark Brawley and Nicole Baerg.“Structural Adjustment, Development and Democracy: New Theories of International Trade Adjustment,” with Mark R. Brawley in International Studies Review, Vol. 9 (4) Winter (2007).

Selected Research in Progress:

Banking on trust: Exploring the relationship between financial inclusion, trust and politics in the UK (with Jon Slapin)

Dividends of Power (Unpublished book manuscript)

Competitive Grants and Awards:

A Quantitative Textual Approach of the European Consensus Method of interpretation in the European Court of Human Rights with Jon Slapin, Panos Kapotas, Vassilis P Tzevelekos, Denise Traber, Hauke Licht, and Kushtrim Istrefi. Swiss Network for International Studies (SNIS), 238,228 CHF (2020-2022).

What shapes public support for COVID-related economic policy interventions? An experimental approach, Collaboration Seed Funding, University of Melbourn, with Brendan Churchill, Jeff Chwieroth, and Andrew Walter AUS $20,000 and Systemic Risk Centre, London School of Economics 12,000 GBP (2020-2021).

Mercator Fellow, Collaborative Research Ceneter 884: Political Economy of Reforms, 10,000 EUR (2018-2021).

Collaborative Research Centre 884: Political Economy of Reforms.” Project C4 with project P.I.’s Thomas Gschwend, Heiner Stuckenschmidt and Nicole Baerg (Mercator Follow) 547,200 EUR & Project B6 with project P.I.’s Carsten Trenkler, Simone Paolo Ponzetto, and Nicole Baerg (Mercator Follow) 410,400 EUR (2018-2021).

MZES Project “Signaling Good Governance” University of Mannheim. 47,000 EUR (2014).

Anreizprogramm zur Berufungl Einstellung von Frauen an den Hochschulen des Landes Baden Wurttemberg. 47,500 EUR (2014).

Lehrprogramm fur Juniorprofessuren, University of Mannheim. 10,000 EUR (2014).

Collaborative Research Centre 884: Political Economy of Reforms. Project C4: Measuring a Common Space and the Dynamics of Reform Positions”, Deutsche Forschungsgemeinschaft (DFG)- Project Co-PI with Thomas Gschwend, Heiner Stuckenschmidt and Will Lowe and associate project members Sven-Oliver Proksch and James Lo. 372,000 EUR (2014-2107).

Invited Talks, Conference Presentations, and Posters:

Università degli Studi di Milano, Milan, 2025.
Lund University, Lund, 2024.
University of British Columbia (Okanagan), Kelowna, 2024.
NIER, Workshop on Advances in Central Banking, London, 2024.
University of Laval, Quebec City, 2023.
University College London, London, 2023.
Bank of England, London, 2021.
MPIfG: Workshop The Politics of Macroeconomic Policies, Virtual, 2021.
American Political Science Association, Virtual, 2020.
European Political Science Association, Virtual, 2020.
Political Economy Speaker Series, Konstanz, 2019.
IPE Speakers Series, London School of Economics, London, 2019.
European Semeter Conference, Pisa, 2019.
International Political Economy Society Meeting, San Diego, 2019.
European Political Science Association, Belfast, 2019.
Scuola Normale Superiore, Florence, 2018.
European Central Bank, DG Communications, Frankfurt, 2018
University of Strathclyde, Glasgow, 2018.
International Political Economy Society meeting, Boston, 2018.
American Political Science Association, Boston, 2018. European Political Science Association, Vienna, 2018.
Institut Barcelona d’Estudis Internacionals, Barcelona, 2017.
American Political Science Association, San Francisco, 2017.
PoliInfomatics Workshop, University of Washington, 2017.
European Political Science Association, Milan, 2017.
Bank of Japan’s Institute for Monetary and Economic Studies, 2017.
School Seminar Talk, University of Kobe, Kobe, 2017.
Midwest Political Science Association, Chicago, 2017.
Inequality and Fairness, Political Economy of Reforms, Mannheim, 2016.
European Political Science Association Meeting, Brussels, 2016.
Amsterdam Text Analysis Conference, Amsterdam, 2016.
IPE Speakers Series, London School of Economics, London, 2016.
Virtual IPES” International Political Economy Society, September 2015.
APSA Political Communication Pre-Conference, September 2015.
Monetary Policy and Central Banking, Princeton, February 2015.
Southern Economic Association Meeting, Atlanta, November 2014.
American Political Science Association Meeting, Washington, D.C., September, 2014.
Crisis, Institutions, and Banking Union, Berlin, Germany, June 2014.
GDG Speakers Series at the University of St. Gallen, Switzerland, May 2014.
Society for Labor Economics, Arlington, VA, May 2014
Speaker Series, University of California at Merced, CA, November 2013.
International Political Economy Society meeting, Claremont, CA, October 2013.
Visions in Methodology, Florida State University, FL, March 2013.
American Political Science Association Meeting, New Orleans, LA., September, 2012
Midwest Political Science Association Meeting, Chicago, IL., May, 2010.
Southern Economic Association Meeting, Washington D.C., November, 2008.
International Political Economy Society Meeting, Stanford University, November, 2007.
ESRC Research Methods Festival, Oxford University, England, 2006.
International Studies Association Meeting, San Diego, 2006.

Teaching:

Advanced Text Analysis, University Bergen (Spring 2022).
Quantitative Text Analysis, Waseda Summer Research Course, Tokyo (Summer 2019).
Quantitative Text Analysis, University of Essex Summer School, (Summer 2023, 2021, 2020, 2019, 2018, 2017).
EITM Europe Summer School: Automatic Text Analysis and Machine Learning, (Summer 2016, 2018).
Document Classification and Machine Learning Workshop, University of Vienna (Spring 2018).
Zurich Summer School for Women in Political Methodology, (Summer, 2017).
Document Classification and Machine Learning Workshop, University of Glasgow (Spring 2017).

Graduate: Introduction to International Political Economy, Political Economy, Research Design, Comparative Political Economy, Politics of Public Policy
Undergraduate: The EU and the Politics of Economic Policy Making, Introduction to International Political Economy, Methods for International Relations, International Organizations: Money and Finance.

PhD Students: Dissertation Committee Supervisor or Committee Member: Yen-Chieh Liao (Supervisor), Jakob Willisch (Supervisor), Brittney Bolin (Member), Sonja Pohle (Member)

Postdoc Students: Colin Krainin, Ph.D.

Other Employment Experience:

Senior Visiting Fellow, London School of Economics and Political Science, Data Science Institute (2023 – present)
Senior Research Data Scientist, Advanced Analytics, Bank of England, 2021-2023.
Adjunct Professor, Business and Political Economy Program, Stern School of Business, New York University (London), 2021 – 2022
Intern, Federal Reserve Bank of Atlanta, Research Department, Atlanta, USA., 2008 to 2013
Program Assistant, Emory University’s European Politics Summer Study Abroad Program, Berlin, Germany, 2010, 2011, 2012.
International Data Support Officer, University of Manchester, England, 2006 to 2007.
Data Lab Assistant, McGill University, Montreal, Canada, 2004 to 2006.

Professional Activities and Service:

Review for Bank Politics: Structural Reform in Comparative Perspective. By David Howarth and Scott James. Oxford: Oxford University Press, 2023. 384p in Perspectives on Politics.

Special Issue Managing Guest Editor: Central Bank Communication and Accountability, European Journal of Political Economy 2021.
Political Economy Section Award Committees 2020
APSA 2020 IPE Division co-Chair
Essex Summer School co-Director (2019-2021)
Visions in Methodology (VIM): Mentoring co-Chair (2018-2021)

Reviewer: American Political Science Review, American Journal of Political Science, British Journal of Political Science, Comparative Political Studies, Economics and Politics, European Economic Review, European Union Politics, Nature (Humanities and Social Sciences Communications), International Interactions, International Studies Quarterly, Journal of European Public Policy, Journal of International Development, Journal of Money, Credit and Banking, Journal of Politics, Legislative Studies Quarterly, Macroeconomic Dynamics, Political Research Quarterly, Political Science Research and Methods, Public Choice, Public Opinion Quarterly, Social Science and Humanities Research Council of Canada, and World Politics.

Editorial Board: Nature (Humanities and Social Sciences Communications)

Conference Organization: Opportunities and Challenges in Economic Policy Communications (with James Cross and Silvia Calò), January 17th, 2020, at the Central Bank of Ireland. Computational Linguistics in Political Science: What Have You Done for Me Lately Workshop Co-chair (with Will Lowe). October 31 to November 1, 2014 at the University of Mannheim and Joint MZES-SFB Workshop: Political Forecasting. December 18, 2015 at the University of Mannheim.

Statistical and Computer Skills:

R, Python, Natural Language Processing